# Generated by Django 2.2.6 on 2019-11-20 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to='loja.Loja')),
            ],
        ),
    ]
