# Generated by Django 2.2.6 on 2019-11-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
