# Generated by Django 2.2.6 on 2019-11-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_auto_20191123_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compra_loja', to='loja.Loja'),
            preserve_default=False,
        ),
    ]
