# Generated by Django 2.2.6 on 2019-11-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_compra_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_complement',
        ),
    ]
