# Generated by Django 2.2.6 on 2019-11-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_remove_cliente_cliente_complement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='local',
            new_name='andar',
        ),
        migrations.AddField(
            model_name='loja',
            name='lote',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
