# Generated by Django 2.2.6 on 2019-11-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_funcionario_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='email',
        ),
    ]
