# Generated by Django 2.2.6 on 2019-11-20 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_funcionario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcionario_complement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complement', to=settings.AUTH_USER_MODEL),
        ),
    ]
