# Generated by Django 2.2.6 on 2019-11-23 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191120_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcionario_complement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complemento', to=settings.AUTH_USER_MODEL),
        ),
    ]
