# Generated by Django 2.2.6 on 2019-11-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20191123_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
