# Generated by Django 2.2.6 on 2019-11-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
